# Generated by Django 5.2 on 2025-04-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_rename_agendamento_scheduling'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professor',
            new_name='Teacher',
        ),
    ]
