# Generated by Django 5.2 on 2025-04-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendamento',
            new_name='Scheduling',
        ),
    ]
