# Generated by Django 5.2 on 2025-05-01 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_aluno_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
