# Generated by Django 5.2 on 2025-05-02 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_aluno_professor_alter_aula_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='titulo',
            new_name='instrumento',
        ),
    ]
