# Generated by Django 5.2 on 2025-05-02 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_rename_titulo_aula_instrumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='idade',
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.CharField(default='sem email', max_length=50),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.IntegerField(default=0, max_length=15),
        ),
    ]
