# Generated by Django 5.2 on 2025-05-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_remove_aluno_idade_aluno_data_nascimento_aluno_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.IntegerField(max_length=15),
        ),
    ]
