# Generated by Django 5.2 on 2025-05-02 21:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_alter_aluno_email_alter_aluno_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_pagamento', models.DateField(default=datetime.date.today)),
                ('referente_ao_mes', models.CharField(max_length=20)),
                ('foi_pago', models.BooleanField(default=True)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('transferencia', 'Transferência'), ('boleto', 'Boleto'), ('outro', 'Outro')], default='pix', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.aluno')),
            ],
        ),
    ]
