# Generated by Django 5.2 on 2025-05-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
